# makefile to use Scott Lawrence's "Genroms" tool to build 
# rom files from the intel hex file

TARGBASE := lloader

DEPNENDS := \
	    examine.asm \
	    input.asm \
	    memprobe.asm \
	    print.asm

include ../Common/approm.mak
