# makefile to use the basicusr core makefile to 
# generate a .BAS RC2014 Basic program

TARGBASE := tmstests

DEPFILES := \
	tmstests.asm 

include ../Common/basicusr.mak

test: clean all
	


edit:
	open llvdstrp.asm toolbox.asm ../Common/hardware.asm

.PHONY: edit
