# makefile to use Scott Lawrence's "Genroms" tool to build 
# rom files from the intel hex file

TARGBASE := baslload

# set our ram load location to C000
# MAKE SURE this matches the .org!
TOPRAM  := C0

include ../Common/basicusr.mak
